# Generated by Django 3.0.3 on 2020-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.CharField(max_length=32, verbose_name='学号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('college', models.CharField(max_length=32, verbose_name='学院')),
                ('stuclass', models.CharField(max_length=64, verbose_name='班级')),
                ('location', models.CharField(max_length=32, verbose_name='地点')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('remain', models.SmallIntegerField(verbose_name='余量')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
    ]
