# Generated by Django 3.1.4 on 2021-01-25 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='role',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='modified_time',
        ),
        migrations.AddField(
            model_name='permission',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
    ]
