# Generated by Django 3.1.4 on 2021-03-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210125_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['create_time']},
        ),
    ]
